# Generated by Django 4.1.7 on 2023-03-14 12:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("surname", models.CharField(max_length=200)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(max_length=100)),
                ("occupation", models.CharField(max_length=200)),
                ("previous_massage", models.CharField(default="", max_length=200)),
                ("salon_choice", models.CharField(default="", max_length=200)),
                ("frequency", models.CharField(default="", max_length=200)),
                ("referral", models.CharField(default="", max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Massage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("massage_date", models.DateTimeField(blank=True, null=True)),
                ("reason_for_visit", models.TextField(default="")),
                ("kind", models.CharField(max_length=300)),
                ("massage_notes", models.TextField(default="")),
                ("next_visit", models.TextField(default="")),
                ("recommendations", models.TextField(default="")),
                ("personal_notes", models.TextField(default="")),
                ("duration", models.CharField(default="", max_length=200)),
                ("amount", models.IntegerField()),
                ("discount", models.CharField(default="", max_length=200)),
                ("repeat_visit", models.BooleanField(default=False)),
                ("added", models.DateTimeField(auto_now_add=True)),
                ("changed", models.DateTimeField(auto_now=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="web.customer"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
