# Generated by Django 4.1.7 on 2023-05-02 10:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("surname", models.CharField(default="", max_length=200, null=True)),
                ("email", models.EmailField(default="", max_length=254, null=True)),
                ("phone", models.CharField(default="", max_length=100, null=True)),
                ("occupation", models.CharField(default="", max_length=200, null=True)),
                ("previous_massage", models.BooleanField(default=False)),
                ("salon_choice", models.CharField(default="", max_length=200)),
                ("frequency", models.CharField(default="", max_length=200)),
                ("referral", models.CharField(default="", max_length=200)),
                (
                    "external_id",
                    models.CharField(blank=True, default="", max_length=50, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "external_id",
                    models.CharField(blank=True, default="", max_length=50, null=True),
                ),
                (
                    "service_group",
                    models.CharField(default="", max_length=200, null=True),
                ),
                ("price", models.CharField(default="", max_length=200, null=True)),
                (
                    "massage_name",
                    models.CharField(default="", max_length=200, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "external_id",
                    models.CharField(default="", max_length=200, null=True),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Massage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField(blank=True, null=True)),
                ("reason_for_visit", models.TextField(default="")),
                ("kind", models.CharField(max_length=300)),
                ("massage_notes", models.TextField(default="")),
                ("next_visit", models.TextField(blank=True, default="")),
                ("recommendations", models.TextField(blank=True, default="")),
                ("personal_notes", models.TextField(blank=True, default="")),
                ("duration", models.CharField(default="", max_length=200)),
                ("amount", models.CharField(default="", max_length=200)),
                ("discount", models.CharField(blank=True, default="", max_length=200)),
                (
                    "discount_reason",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("repeat_visit", models.BooleanField(default=False)),
                ("status", models.CharField(blank=True, default="", max_length=200)),
                (
                    "external_id",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("added", models.DateTimeField(auto_now_add=True)),
                ("changed", models.DateTimeField(auto_now=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="web.customer"
                    ),
                ),
                (
                    "massage_name",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="web.service",
                    ),
                ),
                (
                    "therapist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
