# Generated by Django 4.1.7 on 2023-05-02 10:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="frequency",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AlterField(
            model_name="customer",
            name="occupation",
            field=models.CharField(blank=True, default="", max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="customer",
            name="referral",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AlterField(
            model_name="customer",
            name="salon_choice",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
    ]
