# Generated by Django 4.1.7 on 2023-03-18 18:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="previous_massage",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="massage",
            name="amount",
            field=models.CharField(default="", max_length=200),
        ),
        migrations.AlterField(
            model_name="massage",
            name="discount",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AlterField(
            model_name="massage",
            name="next_visit",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="massage",
            name="personal_notes",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="massage",
            name="recommendations",
            field=models.TextField(blank=True, default=""),
        ),
    ]
