# Generated by Django 4.1.7 on 2023-03-20 14:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0002_alter_customer_previous_massage_alter_massage_amount_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="massage",
            old_name="user",
            new_name="therapist",
        ),
    ]
