# Generated by Django 4.1.7 on 2023-03-26 08:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0003_rename_user_massage_therapist"),
    ]

    operations = [
        migrations.AddField(
            model_name="massage",
            name="discount_reason",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
    ]
