# Generated by Django 4.1.7 on 2023-05-02 11:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0003_alter_massage_massage_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="massage",
            old_name="massage_name",
            new_name="service",
        ),
        migrations.RenameField(
            model_name="service",
            old_name="massage_name",
            new_name="name",
        ),
    ]
