# Generated by Django 4.1.7 on 2023-04-07 10:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0004_massage_discount_reason"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="external_id",
            field=models.CharField(blank=True, default="", max_length=50, null=True),
        ),
    ]
