# Generated by Django 4.1.7 on 2023-05-03 10:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0004_rename_massage_name_massage_service_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="duration",
            field=models.CharField(default="", max_length=200, null=True),
        ),
    ]
