# Generated by Django 4.1.7 on 2023-04-24 15:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0005_customer_external_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="massage",
            name="status",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
    ]
