# Generated by Django 4.1.7 on 2023-05-03 13:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0005_service_duration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="duration",
            field=models.IntegerField(default=0),
        ),
    ]
