# Generated by Django 4.1.7 on 2023-05-03 13:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0006_alter_service_duration"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="time_before",
            field=models.IntegerField(default=0),
        ),
    ]
