# Generated by Django 4.1.7 on 2023-04-24 15:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0007_massage_service"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="email",
            field=models.EmailField(default="", max_length=254, null=True),
        ),
    ]
