# Generated by Django 4.1.7 on 2023-04-24 15:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0008_alter_customer_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="occupation",
            field=models.CharField(default="", max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="customer",
            name="phone",
            field=models.CharField(default="", max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="customer",
            name="surname",
            field=models.CharField(default="", max_length=200, null=True),
        ),
    ]
