# Generated by Django 4.1.7 on 2023-04-25 13:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0009_alter_customer_occupation_alter_customer_phone_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "external_id",
                    models.CharField(blank=True, default="", max_length=50, null=True),
                ),
                ("name", models.CharField(default="", max_length=200, null=True)),
                ("price", models.CharField(default="", max_length=200, null=True)),
                (
                    "massage_type",
                    models.CharField(default="", max_length=200, null=True),
                ),
            ],
        ),
    ]
