# Generated by Django 4.1.7 on 2023-05-04 11:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0010_service_time_after"),
    ]

    operations = [
        migrations.AddField(
            model_name="massage",
            name="massage_end",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="massage",
            name="massage_start",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="massage",
            name="massage_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
