# Generated by Django 4.1.7 on 2023-04-25 14:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0010_service"),
    ]

    operations = [
        migrations.RenameField(
            model_name="service",
            old_name="massage_type",
            new_name="massage_name",
        ),
        migrations.RenameField(
            model_name="service",
            old_name="name",
            new_name="service_group",
        ),
    ]
