# Generated by Django 4.1.7 on 2023-05-08 12:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0011_massage_massage_end_massage_massage_start_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="massage",
            old_name="date",
            new_name="date",
        ),
        migrations.RenameField(
            model_name="massage",
            old_name="end",
            new_name="end",
        ),
        migrations.RenameField(
            model_name="massage",
            old_name="massage_notes",
            new_name="notes",
        ),
        migrations.RenameField(
            model_name="massage",
            old_name="start",
            new_name="start",
        ),
    ]
