# Generated by Django 4.1.7 on 2023-05-09 13:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0012_rename_massage_date_massage_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="massage",
            name="amount",
            field=models.IntegerField(default=""),
        ),
        migrations.AlterField(
            model_name="massage",
            name="discount",
            field=models.IntegerField(blank=True, default=""),
        ),
    ]
