# Generated by Django 4.1.7 on 2023-05-01 11:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0012_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="massage",
            name="external_id",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
    ]
