# Generated by Django 4.1.7 on 2023-05-09 13:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0013_alter_massage_amount_alter_massage_discount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="massage",
            name="amount",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="massage",
            name="discount",
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
