# Generated by Django 4.1.7 on 2023-05-01 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0014_rename_profile_userprofile"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="massage",
            name="service",
        ),
        migrations.AddField(
            model_name="massage",
            name="massage_name",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="web.service"
            ),
        ),
    ]
