# Generated by Django 4.1.7 on 2023-05-09 13:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0014_alter_massage_amount_alter_massage_discount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="price",
            field=models.IntegerField(default=0, null=True),
        ),
    ]
