# Generated by Django 4.1.7 on 2023-05-10 18:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0016_alter_massage_duration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="massage",
            name="external_id",
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
