# Generated by Django 4.1.7 on 2023-05-13 20:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0018_alter_massage_amount_alter_massage_discount_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="massage",
            name="date",
        ),
    ]
