# Generated by Django 4.1.7 on 2023-09-11 07:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0021_service_payout"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="payout",
            field=models.IntegerField(default=0, null=True),
        ),
    ]
