# Generated by Django 4.1.7 on 2024-01-03 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0022_alter_service_payout"),
    ]

    operations = [
        migrations.CreateModel(
            name="Price",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateTimeField(blank=True, null=True)),
                ("end_date", models.DateTimeField(blank=True, null=True)),
                ("cost", models.IntegerField(default=0, null=True)),
                ("payment", models.IntegerField(default=0, null=True)),
                (
                    "service",
                    models.ForeignKey(
                        default="",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="service_record",
                        to="web.service",
                    ),
                ),
            ],
        ),
    ]
