# Generated by Django 4.1.7 on 2024-01-03 12:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0023_price"),
    ]

    operations = [
        migrations.RenameField(
            model_name="price",
            old_name="payment",
            new_name="payout",
        ),
    ]
