# Generated by Django 4.1.7 on 2024-01-04 10:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0024_rename_payment_price_payout"),
    ]

    operations = [
        migrations.AddField(
            model_name="price",
            name="added",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="price",
            name="changed",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
