# Generated by Django 4.1.7 on 2024-04-03 09:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0025_price_added_price_changed"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="added",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="service",
            name="changed",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
